//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.30 at 04:50:35 PM IRST 
//


package com.isc.npsd.sharif.node.entities.schemaobjects.trx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TXR" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MndtReqId" type="{hal:sct:1.0.0}Max35Text"/>
 *                   &lt;element name="CBIC" type="{hal:sct:1.0.0}BICIdentifier"/>
 *                   &lt;element name="DBIC" type="{hal:sct:1.0.0}BICIdentifier"/>
 *                   &lt;element name="MaxAmt" type="{hal:sct:1.0.0}ActiveCurrencyAndAmount" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "txr"
})
@XmlRootElement(name = "TXRList")
public class TXRList {

    @XmlElement(name = "TXR", required = true)
    protected List<TXRList.TXR> txr;

    /**
     * Gets the value of the txr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the txr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTXR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TXRList.TXR }
     * 
     * 
     */
    public List<TXRList.TXR> getTXR() {
        if (txr == null) {
            txr = new ArrayList<TXRList.TXR>();
        }
        return this.txr;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MndtReqId" type="{hal:sct:1.0.0}Max35Text"/>
     *         &lt;element name="CBIC" type="{hal:sct:1.0.0}BICIdentifier"/>
     *         &lt;element name="DBIC" type="{hal:sct:1.0.0}BICIdentifier"/>
     *         &lt;element name="MaxAmt" type="{hal:sct:1.0.0}ActiveCurrencyAndAmount" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mndtReqId",
        "cbic",
        "dbic",
        "maxAmt"
    })
    public static class TXR {
        @XmlElement(name = "MndtReqId", required = true)
        protected String mndtReqId;
        @XmlElement(name = "CBIC", required = true)
        protected String cbic;
        @XmlElement(name = "DBIC", required = true)
        protected String dbic;
        @XmlElement(name = "MaxAmt")
        protected ActiveCurrencyAndAmount maxAmt;

        /**
         * Gets the value of the mndtReqId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMndtReqId() {
            return mndtReqId;
        }

        /**
         * Sets the value of the mndtReqId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMndtReqId(String value) {
            this.mndtReqId = value;
        }

        /**
         * Gets the value of the cbic property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCBIC() {
            return cbic;
        }

        /**
         * Sets the value of the cbic property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCBIC(String value) {
            this.cbic = value;
        }

        /**
         * Gets the value of the dbic property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDBIC() {
            return dbic;
        }

        /**
         * Sets the value of the dbic property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDBIC(String value) {
            this.dbic = value;
        }

        /**
         * Gets the value of the maxAmt property.
         * 
         * @return
         *     possible object is
         *     {@link ActiveCurrencyAndAmount }
         *     
         */
        public ActiveCurrencyAndAmount getMaxAmt() {
            return maxAmt;
        }

        /**
         * Sets the value of the maxAmt property.
         * 
         * @param value
         *     allowed object is
         *     {@link ActiveCurrencyAndAmount }
         *     
         */
        public void setMaxAmt(ActiveCurrencyAndAmount value) {
            this.maxAmt = value;
        }

    }

}
