package com.isc.npsd.sharif.node.entities;

/**
 * Created by A_Ahmady on 9/25/2016.
 */
public enum NodeProperties {

    SHARIF_DB_URL,
    SHARIF_DB_USER,
    SHARIF_DB_PASS,
    SHARIF_DB_RESOURCE,
    SHARIF_DB_POOL_SIZE,
    SHARIF_DB_CONNECTION_TIMEOUT,
    SHARIF_HIBERNATE_SHOW_SQL,
    SHARIF_MID_SEQ_CACHE_SIZE,
    SHARIF_BATCH_SIZE,
    SHARIF_MSG_ID_SEQ_CACHE_SIZE,
    SHARIF_TRANSACTION_TIMEOUT;
}
